#!/bin/bash
# Schnellstart-Anleitung für das GBU Management System

echo "========================================"
echo "GBU Management System - Schnellstart"
echo "========================================"
echo ""

echo "✅ Virtuelle Umgebung erstellt"
echo "✅ Abhängigkeiten installiert"
echo ""

echo "Nächste Schritte:"
echo ""
echo "1. .env Datei anpassen:"
echo "   nano /home/user/GBU_Management/backend/.env"
echo ""
echo "   Ändern Sie:"
echo "   DATABASE_URL=mysql+pymysql://gbu_user:IhrPasswort@localhost/gbu_management"
echo ""
echo "2. Datenbank einrichten:"
echo "   mysql -u root -p"
echo "   > CREATE DATABASE gbu_management CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   > CREATE USER 'gbu_user'@'localhost' IDENTIFIED BY 'IhrPasswort';"
echo "   > GRANT ALL PRIVILEGES ON gbu_management.* TO 'gbu_user'@'localhost';"
echo "   > FLUSH PRIVILEGES;"
echo "   > EXIT;"
echo ""
echo "   mysql -u gbu_user -p gbu_management < /home/user/GBU_Management/database/schema.sql"
echo ""
echo "3. Backend starten:"
echo "   cd /home/user/GBU_Management/backend"
echo "   source venv/bin/activate"
echo "   python app.py"
echo ""
echo "4. Frontend einrichten (in neuem Terminal):"
echo "   cd /home/user/GBU_Management/frontend"
echo "   npm install"
echo "   npm start"
echo ""
echo "5. Im Browser öffnen:"
echo "   http://localhost:3000"
echo ""
echo "   Standard-Login:"
echo "   Benutzername: admin"
echo "   Passwort: admin123"
echo ""
echo "========================================"
